# https://github.com/elastic/elasticsearch-docker
#FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2

# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
FROM docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.2

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
